app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('dcconocidos.urls')),
    path('user_manager', include('django.contrib.auth.urls')),
    path('user_manager/', include('user_manager.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

app/dcconocidos/urls.py
from django.urls import path

from . import views

app_name = 'dcconocidos'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_spot', views.add_spot, name='add_spot'),
    path('create_new_location', views.create_new_location, name='create_new_location'),
]

app/user_manager/urls.py
from django.urls import path
from . import views

app_name = 'user_manager'
urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register_user, name='register'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
]

app/core/models.py
from django.db import models


class Sample(models.Model):
    attachment = models.FileField()

app/dcconocidos/models.py
from django.db import models
from django.contrib.auth.models import User

class Location(models.Model):
    longitude = models.CharField(max_length=200)
    latitude = models.CharField(max_length=200)
    location_name = models.CharField(max_length=200)
    user = models.ForeignKey(
        User, 
        on_delete = models.CASCADE,
        default = 1,
    )

app/user_manager/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True,)
    address = models.CharField(max_length=200, null=True)
    phone_number = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

app/user_manager/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Profile

class createUserForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length = 50)
    last_name = forms.CharField(max_length=50)

    class meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

class profileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['address', 'phone_number']
        labels = {
                "address": _("Street Address"),
                "phone_number": _("Phone Number"),
                }
                

app/core/views.py
from django.shortcuts import render

# Create your views here.

app/dcconocidos/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Location

def index(request):
    if request.user.is_authenticated:
        locations = request.user.location_set.all()
        other_locations = Location.objects.exclude(user=request.user)
    else:
        locations = None
        other_locations = None
    return render(request, 'dcconocidos/index.html', {'locations': locations, 'other_locations':other_locations})

def add_spot(request):
    if request.method == 'POST':
        lng = request.POST['lng']
        lat = request.POST['lat']
        return render(request, 'dcconocidos/add_spot.html', {'lng':lng, 'lat':lat})

def create_new_location(request):
    if request.method == 'POST':
        lng = request.POST['lng']
        lat = request.POST['lat']
        name = request.POST['loc_name']
        new_location = Location(latitude=lat, longitude=lng, location_name=name, user=request.user)
        new_location.save()
    return redirect('/')

app/user_manager/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import createUserForm, profileForm
from .models import Profile

def index(request):
    return HttpResponse("Hello, world. You're at the user manager index.")

def register_user(request):
    #Falta agregar mas datos de los usuarios que piden en enunciado
    form = createUserForm(request.POST or None)
    profile_form = profileForm(request.POST or None)
    if request.method == 'POST':

        if form.is_valid():
            user = form.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            login_user = authenticate(username=username, password=password)

            login(request, login_user)
        else:
            messages.success(request, ("Hubo un problema registrando el usuario, intenta nuevamente."))
        return(redirect('/'))
    else:
        context = {'form': form, 'profile_form': profile_form}
        return render(request, 'user_manager/register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return(redirect('/'))
        else:
            messages.success(request, ("Hubo un problema iniciando sesión, intenta nuevamente."))
            return redirect('/user_manager/login')
    else:
        return render(request, 'user_manager/login.html', {})

def logout_user(request):
    logout(request)
    return(redirect('/'))

app/dcconocidos/templates/dcconocidos/add_spot.html
<!DOCTYPE HTML>
<HTML>
   <HEAD>
      <TITLE>DCConocidos</TITLE>
   </HEAD>
   <BODY>
       {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
       {% endif %}
      <form action="{% url 'dcconocidos:create_new_location' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>Crear nueva ubicacion</h1></legend>

            <label for="name"> Nombre ubicacion: </label>
            <input type="text" name="loc_name">
            
            <input type="text" name="lat" value="{{ lat }}">
            <input type="text" name="lng" value="{{ lng }}">

        </fieldset>
        <input type="submit" value="Guardar">
    </form>
   </BODY>
</HTML>

app/dcconocidos/templates/dcconocidos/index.html
<!DOCTYPE HTML>
<HTML>
   <HEAD>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
         integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
         crossorigin="" />
      <TITLE>DCConocidos</TITLE>
   </HEAD>
   <BODY>
      <h1>DCConocidos</h1>
      {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
      {% endif %}
      {% if user.is_authenticated %}
         <p><a href="{% url 'user_manager:logout' %}">Logout</a></p>

         <p>Verde: Ubicaciones de otros usuarios</p>
         <p>Azul: Tus ubicaciones</p>
         <p>Rojo: Nueva ubicación (doble click para agregar)</p>

         <div id="myMap" style="height: 500px; width:70%;"></div>
         <form action="{% url 'dcconocidos:add_spot' %}" method="post">
            {% csrf_token %}
            <p>Haz doble click en el mapa o ingresa coordenadas para agregar una ubicación</p>
            <label for="lat">Latitud: </label>
            <input type="text" name="lat" id="lat">
            <label for="lnt">Longitud: </label>
            <input type="text" name="lng" id="lng">

            <input type="submit" value="Registrar ubicacion">
         </form>

         {% if locations %}
            <h3> Tus ubicaciones </h3>
            <ol>
               {% for location in locations %}
                     <li>{{ location.location_name }}, {{ location.longitude }}, {{ location.latitude }}</li>
               {% endfor %}
            </ol>
         {% endif %}

      {% else %}
         <p><a href="{% url 'user_manager:register' %}">Registrarse</a></p>
         <p><a href="{% url 'user_manager:login' %}">Login</a></p>

      {% endif %}

      <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
         integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
         crossorigin=""></script>
      <script>
         let myMap = L.map('myMap').setView([-33.498993886516175, -70.61490567393622], 15);

         L.tileLayer(`https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png`, {
            maxZoom: 18,
         }).addTo(myMap);

         var greenIcon = new L.Icon({
            iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-green.png',
            shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
            iconSize: [25, 41],
            iconAnchor: [12, 41],
            popupAnchor: [1, -34],
            shadowSize: [41, 41]
          });

          var redIcon = new L.Icon({
            iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-red.png',
            shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
            iconSize: [25, 41],
            iconAnchor: [12, 41],
            popupAnchor: [1, -34],
            shadowSize: [41, 41]
          });

         var marker;

         myMap.doubleClickZoom.disable()
         myMap.on('dblclick', e => {
            let latLng = myMap.mouseEventToLatLng(e.originalEvent);

            document.getElementById('lat').value = latLng.lat;
            document.getElementById('lng').value = latLng.lng;

            if(marker){
               myMap.removeLayer(marker)
            }

            marker = L.marker([latLng.lat, latLng.lng], {icon: redIcon}).addTo(myMap)
         });

         {% if locations %}
            {% for location in locations %}
               var marker_location;
               marker_location = L.marker(["{{ location.latitude }}", "{{ location.longitude }}"], {}).addTo(myMap);

            {% endfor %}
         {% endif %}

         {% if other_locations %}
            {% for location in other_locations %}
               var marker_other_location;
               marker_other_location = L.marker(["{{ location.latitude }}", "{{ location.longitude }}"], {icon:greenIcon}).addTo(myMap);

            {% endfor %}
         {% endif %}
         
      </script>
   </BODY>
</HTML>

app/user_manager/templates/user_manager/login.html
<!DOCTYPE HTML>
<HTML>
   <HEAD>
      <TITLE>DCConocidos</TITLE>
   </HEAD>
   <BODY>
       {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
       {% endif %}
      <form action="{% url 'user_manager:login' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>Log In</h1></legend>

            <label for="username"> Usuario: </label>
            <input type="text" name="username">
            
            <label for="password"> Contraseña: </label>
            <input type="password" name="password">

        </fieldset>
        <input type="submit" value="Send">
    </form>
   </BODY>
</HTML>

app/user_manager/templates/user_manager/register.html
<!DOCTYPE HTML>
<HTML>
   <HEAD>
      <TITLE>DCConocidos</TITLE>
   </HEAD>
   <BODY>

      {% if form.errors %}
         <p> Hubo un error con su formulario de registro </p>
      {% endif %}

      <form action="{% url 'user_manager:register' %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <legend><h1>Registrarse</h1></legend>

            <div class="form-field">
                {{form.first_name.label_tag}}
                {{form.first_name}}
            </div>
            <div class="form-field">
                {{form.last_name.label_tag}}
                {{form.last_name}}
            </div>
            <div class="form-field">
                {{form.username.errors}}
                {{form.username.label_tag}}
                {{form.username}}
            </div>
            <div class="form-field">
                {{form.email.label_tag}}
                {{form.email}}
            </div>
            <div class="form-field">
                {{profile_form.address.label_tag}}
                {{profile_form.address}}
            </div>
            <div class="form-field">
                {{profile_form.phone_number.label_tag}}
                {{profile_form.phone_number}}
            </div>
            <div class="form-field">
                {{form.password1.errors}}
                {{form.password1.label_tag}}
                {{form.password1}}
            </div>
            <div class="form-field">
                {{form.password2.errors}}
                {{form.password2.label_tag}}
                {{form.password2}}
            </div>

        </fieldset>
        <input type="submit" value="Send">
    </form>
   </BODY>
</HTML>

app/user_manager/templates/user_manager/register_old.html
<!DOCTYPE HTML>
<HTML>
   <HEAD>
      <TITLE>DCConocidos</TITLE>
   </HEAD>
   <BODY>

      {% if form.errors %}
         <p> Hubo un error con su formulario de registro </p>
      {% endif %}

      <form action="{% url 'user_manager:register' %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <legend><h1>Registrarse</h1></legend>

            {{ form.as_p }}

        </fieldset>
        <input type="submit" value="Send">
    </form>
   </BODY>
</HTML>